# Generated by Django 3.2.12 on 2022-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_videoupload_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
